export const SECTIONS = [
  {
    id: "introduction",
    title: "Introduction",
    content:
      "The useScrollSpy hook is a powerful utility for tracking which section of your page is currently visible in the viewport. It uses the Intersection Observer API under the hood, providing an efficient and performant way to monitor scroll position without expensive scroll event listeners. This hook is particularly useful for creating navigation menus that highlight the current section, implementing table of contents with active state indicators, or building any UI that needs to respond to scroll position changes. Unlike traditional scroll event listeners that fire continuously during scrolling, the Intersection Observer API only triggers callbacks when elements enter or exit the viewport, resulting in significantly better performance. This makes useScrollSpy ideal for content-heavy pages, documentation sites, and long-form articles where smooth scrolling experience is crucial. The hook handles all the complexity of setting up observers, calculating intersection thresholds, and managing state updates, leaving you with a simple, declarative API that returns the currently active section ID.",
  },
  {
    id: "getting-started",
    title: "Getting Started",
    content:
      "To get started with useScrollSpy, you'll need to install the package and import the hook into your React component. The hook accepts an object with two properties: headings (an array of HTMLHeadingElement references) and offset (a number representing the pixel offset from the top of the viewport). First, collect references to your heading elements using React refs or by querying the DOM. Then pass these references along with your desired offset to the hook. The offset parameter is particularly important when your page has fixed headers or navigation bars—you'll want to set this value to match the height of those fixed elements so the scroll spy activates at the right position. For example, if you have a 64px tall fixed header, set offset to 64. The hook will then consider a heading as 'active' when it crosses that 64px threshold from the top of the viewport. Installation is straightforward: simply add the package to your project using npm or yarn, then import the useScrollSpy hook from the package. Make sure your heading elements have unique ID attributes, as these are what the hook uses to identify which section is currently active.",
  },
  {
    id: "basic-usage",
    title: "Basic Usage",
    content:
      "Here's a simple example of how to use the useScrollSpy hook in your application. Start by creating refs for your heading elements, then pass them to the hook along with your desired offset value. The hook will automatically set up intersection observers for each heading and track which one is currently in view. You can use this active ID to conditionally style navigation links or any other UI elements. A typical implementation involves three steps: First, collect your heading elements—you can do this with useRef for individual headings, or by querying the DOM in a useEffect for dynamic content. Second, pass the headings array and offset to useScrollSpy. Third, use the returned activeHeadingId to apply active styles to your navigation. The beauty of this approach is its simplicity: you don't need to worry about scroll event throttling, intersection calculations, or cleanup—the hook handles all of that internally. For dynamic content that might change after initial render, make sure to update your headings array in a useEffect when the content changes. The hook will automatically clean up old observers and create new ones when the headings array changes.",
  },
  {
    id: "api-reference",
    title: "API Reference",
    content:
      "The useScrollSpy hook accepts a configuration object with the following properties: headings (HTMLHeadingElement[]) - an array of heading DOM elements to observe. These should be the actual DOM nodes, not React refs. If using refs, pass ref.current values. Each heading must have a unique id attribute. offset (number) - the pixel offset from the top of the viewport where the detection line is positioned. This is typically set to match the height of any fixed headers in your layout. The hook returns a string or undefined representing the ID of the currently active heading element. It returns undefined when no heading is currently in the detection zone (for example, when the page is scrolled to the very top before any headings). The hook automatically handles edge cases like fast scrolling, reaching the bottom of the page, and dynamic content changes. When the user scrolls to the very bottom of the page, the last heading is automatically activated even if it hasn't crossed the detection threshold. Similarly, when at the very top, the first heading is activated if it's visible. These behaviors ensure a natural and intuitive user experience.",
  },
  {
    id: "advanced-patterns",
    title: "Advanced Patterns",
    content:
      "For complex use cases, consider these advanced patterns: Dynamic Content - when your page content can change (like in a CMS or when loading more content), update the headings array whenever content changes. Use a useEffect with appropriate dependencies to re-query the DOM and update the headings state. The hook will automatically re-initialize observers when the headings array changes. Nested Scrolling - by default, the hook observes intersection relative to the viewport. For custom scroll containers, you may need to modify the observer's root option. Consider creating a variant of the hook that accepts a scroll container ref. Smooth Scroll Integration - combine useScrollSpy with smooth scrolling for a complete navigation experience. When a user clicks a nav link, use scrollIntoView with behavior: 'smooth' or window.scrollTo with calculated positions. Make sure to account for your offset value so the heading lands in the correct position. Performance Optimization - for pages with many headings, consider debouncing state updates or using React.memo to prevent unnecessary re-renders of navigation components. The hook itself is already optimized, but your consuming components might benefit from additional memoization.",
  },
  {
    id: "implementation-details",
    title: "Implementation Details",
    content:
      "The hook uses Intersection Observer as the core tracking mechanism, which provides significant performance benefits over traditional scroll listeners. A single observer instance monitors all headings simultaneously, using a carefully calculated rootMargin to position the detection zone. The observation area height is dynamically set to match the smallest heading height in the list—this ensures only one heading can ever be in the detection zone at a time, preventing flickering or ambiguous states. The rootMargin is calculated as: top margin equal to negative offset (to push the detection zone down from the viewport top), and bottom margin calculated to leave only a thin strip at the offset position. This creates a precise detection line rather than a large area. The scrollend event listener handles edge cases that can occur during fast scrolling. Due to browser optimization, intersection callbacks might be skipped when scrolling very quickly. The scrollend handler catches these cases by checking if we're at the very top or bottom of the page and updating the active heading accordingly. All observers and event listeners are properly cleaned up when the component unmounts or when dependencies change, preventing memory leaks and stale references.",
  },
  {
    id: "troubleshooting",
    title: "Troubleshooting",
    content:
      "Common issues and their solutions: No Active Heading - if no heading ever becomes active, first check that your heading elements have valid id attributes. The hook uses these IDs to track and report the active section. Also verify that you're passing actual DOM elements (not React refs) to the hook. If using refs, pass ref.current. Wrong Heading Active - if the wrong heading is highlighted, your offset value might not match your layout. Measure the actual height of your fixed header and use that value. You can add a visual debug indicator (like a colored line) at the offset position to verify it's in the right place. Flickering State - rapid switching between headings usually occurs when headings are smaller than the detection zone. Ensure your sections have enough content between headings, or adjust your layout so headings have sufficient height. Browser Compatibility - the Intersection Observer API is supported in all modern browsers including Chrome, Firefox, Safari, and Edge. For older browsers, you may need a polyfill. Late Initialization - if headings aren't detected on initial load, make sure you're collecting heading references after the DOM has fully rendered. Use useEffect with an empty dependency array or wait for your content to load before initializing.",
  },
  {
    id: "best-practices",
    title: "Best Practices",
    content:
      "Follow these best practices for optimal results: Stable References - memoize your headings array using useMemo or store it in state that only updates when content actually changes. Recreating the array on every render will cause unnecessary observer teardown and recreation, hurting performance. Meaningful IDs - use descriptive, URL-friendly IDs for your headings (like 'getting-started' instead of 'section-1'). This enables deep linking and makes your code more maintainable. Users can share links directly to specific sections of your content. Appropriate Offset - don't guess your offset value—measure it. Use browser dev tools to find the exact height of your fixed elements. Remember to account for any padding or margins. If your fixed header height can change (like on mobile), consider making the offset responsive. Accessibility - ensure your active state indicators don't rely solely on color. Use additional visual cues like font weight, borders, or icons. Make sure your navigation is keyboard accessible and that active states are announced to screen readers. Also consider focus management when users click navigation links. Test Thoroughly - test your scroll spy with various content lengths, different viewport sizes, and both slow and fast scrolling. Edge cases often appear with very short sections or when content doesn't fill the entire viewport.",
  },
  {
    id: "examples",
    title: "Examples",
    content:
      "Real-world use cases where useScrollSpy shines: Documentation Sites - create a table of contents sidebar that highlights the current section as users read through documentation. This helps users understand where they are in long documents and enables quick navigation to specific topics. Landing Pages - build navigation that updates as visitors scroll through different sections of your marketing page. Highlight 'Features' when they're viewing features, 'Pricing' when they reach pricing, etc. This creates a polished, professional feel and helps with orientation. Article Readers - implement progress indicators for long-form content. Combine useScrollSpy with a visual progress bar or reading time estimator. You can also use it to lazy-load comments or related articles when users reach the end of an article. Dashboard Interfaces - track which panel or widget is currently in view in scrollable dashboards. This can trigger loading of panel-specific data only when needed, or highlight the active panel in a minimap navigation. Single Page Applications - create scroll-based navigation that updates the URL hash without full page reloads. Users can bookmark specific sections and share deep links. Combine with smooth scrolling for a app-like navigation experience.",
  },
  {
    id: "conclusion",
    title: "Conclusion",
    content:
      "The useScrollSpy hook provides a robust, performant solution for tracking scroll position in React applications. By leveraging the Intersection Observer API instead of scroll event listeners, it delivers smooth performance even on content-heavy pages. The careful handling of edge cases—like fast scrolling and reaching page boundaries—ensures reliable behavior in real-world usage. Whether you're building documentation, marketing pages, or complex web applications, useScrollSpy gives you the foundation for scroll-aware user interfaces without the complexity of managing observers yourself. The simple API—just pass your headings and offset, get back the active ID—makes it easy to integrate into existing projects or include in new ones. As web applications continue to embrace long-form scrolling content, tools like useScrollSpy become essential for maintaining user orientation and providing intuitive navigation. We hope this hook serves you well in your projects. Happy scrolling, and may your users always know where they are on the page!",
  },
];
